CREATE TABLE IF NOT EXISTS PRODUCTS (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(1024) NOT NULL,
  PRICE NUMERIC(10, 2) NOT NULL,
  QUANTITY INTEGER NOT NULL
);

INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES
  ('iPhone 15 Pro Max', 'Apple iPhone 15 Pro Max 256 GB Black Titanium', 1199.00, 5);