version: '3'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

  order-microservice:
    build:
      context: order-microservice/
    image: order-microservice
    container_name: order-microservice
    depends_on:
      - kafka
    ports:
      - 8081:8081
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PRODUCT_MICROSERVICE_BASE_URL: http://product-microservice:8080

  product-microservice:
    build:
      context: product-microservice/
    image: product-microservice
    container_name: product-microservice
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ORDER_MICROSERVICE_BASE_URL: http://order-microservice:8081
