server:
  port: 8081
spring:
  application:
    name: order-microservice
  datasource:
    url: jdbc:h2:mem:order-microservice
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
api:
  product:
    base-url: ${PRODUCT_MICROSERVICE_BASE_URL}
    get-quantity-uri: /products/{id}/quantity
  kafka:
    update-product-quantity: update-product-quantity-by-id-topic
